# Generated by Django 5.2.17 on 2026-08-29 10:49

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Permission = apps.get_model("auth", "Permission")

    candidate, _ = Role.objects.get_or_create(
        name="candidate",
        defaults={"description": "Candidate can CRUD own resumes"},
    )

    hr, _ = Role.objects.get_or_create(
        name="hr",
        defaults={"description": "HR can view resumes"},
    )

    admin, _ = Role.objects.get_or_create(
        name="admin",
        defaults={"description": "Admin can CRUD all resumes"},
    )

    view_resume = Permission.objects.get(codename="view_resume")
    add_resume = Permission.objects.get(codename="add_resume")
    change_resume = Permission.objects.get(codename="change_resume")
    delete_resume = Permission.objects.get(codename="delete_resume")

    candidate.permissions.set([
        view_resume,
        add_resume,
        change_resume,
        delete_resume,
    ])

    hr.permissions.set([
        view_resume,
    ])

    admin.permissions.set([
        view_resume,
        add_resume,
        change_resume,
        delete_resume,
    ])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
        ("resumes", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]